# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/reco_paper',
                'doc_host': 'https://ryviuszero.github.io',
                'git_url': 'https://github.com/ryviuszero/reco_paper',
                'lib_path': 'reco_paper'},
  'syms': {'reco_paper.core': {'reco_paper.core.foo': ('core.html#foo', 'reco_paper/core.py')}}}
